services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./web:/project
      - ./proto:/project/src/proto
    depends_on:
      - api
      - db
    tty: true
    working_dir: /project/src
    command: /bin/bash -c "bun install && bun run dev"
volumes:
  data:
