name: buf-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buf-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bufbuild/buf-setup-action@v1
      
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
          config: buf.gen.yaml
